### ISSUE TITLE
docker secrets?

### ISSUE THREAD

**Issue by miesgre** [opencast/opencast-docker#98]
Is it posible tu use docker secrets instead of environment params for sensitive data?

**Comment by miesgre** [comment]
Maybe, something like this (https://medium.com/@basi/docker-environment-variables-expanded-from-secrets-8fa70617b3bc) can be added to the images.

**Comment by mtneug** [comment]
The available environment options are more meant for quit tests rather than production deployments. In the latter case, you would rather mount Opencast's configuration files into the container or use secrets and link to them in the configuration folder. Regardless, I agree that we could add support passing secrets in this manner.

The official images from Docker use the patter `<var>_FILE` to point to a file that contains the value for the environment variable `<var>` (see [mysql](https://hub.docker.com/_/mysql/), [mongo](https://hub.docker.com/_/mongo/), [postgres](https://hub.docker.com/_/postgres/)). I would suggest to stick to that pattern.

I will see, when I can implement this feature. It should be easy to implement.

**Comment by mtneug** [comment]
#102 implements this feature. It is available in `latest`, `5.2`, and `next` images.
